Ages/urls.py
from django.urls import path
from . import views
from Ages.views import model_form_upload


app_name = 'Ages'

urlpatterns = [
    path('', model_form_upload, name='Ages'),

]

accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view , name='login_view'),
    path('register/', views.register_view , name='register_view'),
    path('logout/', views.logout , name='logout'),
    path('dashborad/', views.dashborad , name='dashborad'),
]

coralcity/urls.py
from django.contrib import admin
from django.urls import path,include
from graphene_django.views import GraphQLView
from blog.schema import schema
from pages import views
from listings import views
from accounts import views
from contacts import views
from Ages import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('AgesVerification/', include('Ages.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header ="Koralcity control panel"
admin.site.index_title ="Administrators dashboard"
admin.site.site_title ="Control panel"

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.index , name='listings'),
    path('<int:listing_id>/',views.listing , name='listing'),
    path('search/',views.search , name='search'),

]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index , name='index'),
    path('about/', views.about , name='about'),
]

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
       <div class="container" id="message">
       	 <div class="alert alert-{{ message.tags }} alert-dismissable text-center" role="alert">
       	 	<button type="button" data-dismiss="alert" class="close"><span aria-hidden=true>
       	 		&times;
       	 	</span></button>
       	 	<strong>
       	 		{% if  message.level == DEFAULT_MESSAGE_LEVELS.ERROR%}
       	 		    Error:
       	 		{% else %}
       	 		     {{ message.tags|title }}
       	 		{% endif %}
       	 	</strong>
       	 	{{ message }}
       	 </div>
       </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
 {% load static %}
 <!------------------------------------------------ FOOTER SECTION -->
    <footer id="contact">
      <div class="container">
        <div class="row footer-top">
          <div class="col-12 col-md-6">
            <!-- logo -->
            <h3>RealEstate LTD </h3>
            <h3>Explore Real Estate</h3>
          </div>
          <div class="col-12 col-md-6 Newsletter">
            <input type="text" placeholder="Subscribe To Our Newsletter" class="left">
            <button class="newsletter-btn left"></button>
          </div>
        </div>
        <div class="row footer-bottom">
          <div class="col-sm-12 col-md-4 footer-logo">
            <h4>Realestate</h4>
            <p>© 2021 - realestate,<br>All Right Reserved</p>
           
          </div>
          <div class="col-sm-3 col-md-2 footer-column">
            <h5>KoralCity</h5>
            <a href="{% url 'accounts:login_view' %}">Agents</a>
            <a href="{% url 'accounts:register_view' %}">Become an agent</a>
          </div>
          <div class="col-sm-3 col-md-2 footer-column">
            <h5>COMPANY</h5>
            <a href="{% url 'pages:about' %}">About</a>
            <a href="{% url 'accounts:login_view' %}">FAQ</a>
            <a href="{% url 'accounts:login_view' %}">Contact</a>
            <a href="{% url 'accounts:login_view' %}">Social</a>
          </div>          
          <div class="col-sm-3 col-md-2 footer-column">
            <h5>PRODUCT</h5>
            <a href="{% url 'listings:listings' %}">Apartment</a>
            <a href="{% url 'accounts:login_view' %}">How It Works</a>
          </div>
          <div class="col-sm-3 col-md-2 footer-column">
            <h5>SERVICES</h5>
            <a href="{% url 'accounts:login_view' %}">Renting</a>
            <a href="{% url 'accounts:login_view' %}">Selling</a>
            <a href="{% url 'Ages:Ages' %}">AGIS Verification</a>
          </div>
          <div class="col-sm-3 col-md-2">
            <a href=" https://www.facebook.com/Koral-City-ltd-100737889187297"> <img src="{% static './images/facebook.png' %}" height="40" width="40"></a>
            <a href="https://www.instagram.com/koralcityltd/"> <img src="{% static './images/instagram.png' %} "height="40" width="40"></a>
            <a href="https://twitter.com/Koralcityltd"><img src="{% static './images/twitter.png' %} "height="40" width="40"></a>
          </div>
        </div>
      </div>
    </footer>

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
 <header id="home">

<nav class="animate">
        <div class="container">
          <div class="logo left">
            <!-- Logo -->
           
            </li>
          </div>
          <div class="menu-button hide right pointer" style=" color:  black;">
            <span></span>
            <span></span>
            <span></span>
          </div>
          <div class="menu left">
            <div class="page-menu left">
              <!-- Navigation -->
              <li><a href="{% url 'pages:index' %}">Home</a></li>
              <li><a href="{% url 'pages:about' %}">About</a></li>
              
              <li><a href="{% url 'listings:listings' %}">Properties</a></li>
              <li><a href="{% url 'Ages:Ages' %}">Verification</a></li>
              <li><a href="#contact">Contact</a></li>
            </div>
            <div class="registration flex-center">
              <div class="join-us">
                <!-- Join Us Button -->
                    <li class="pointer animate"><a href="{% url 'accounts:login_view' %}">Agents</a>
                 </li>    
                </div>
                  <div class="getting-started">
                    <!-- Get Started Button -->
                   <a href="{% url 'accounts:register_view' %}"><li class="main-btn pointer text-center animate">Become an agent</li></a>
                  </div>
                </div>
                <div class="registration flex-center">
                  <div class="join-us">
                    <!-- Join Us Button -->
                 
              </div>
              <div class="getting-started">
                <!-- Get Started Button -->
              </div>
            </div>
          </div>
        </div>
      </nav>

templates/partials/_topbar.html
  <section id="top-bar" class="animate">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> (810)-080-8038
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> inquiries@coralcity.com
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fab fa-whatsapp"></i>
            </a>
            <a href="#">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fab fa-envelope-open"></i>
            </a>
          </div>
        </div>
      </div>
  </section>