Ages/urls.py
from django.urls import path
from . import views
from Ages.views import model_form_upload


app_name = 'Ages'

urlpatterns = [
    path('', model_form_upload, name='Ages'),

]

coralcity/urls.py
from django.contrib import admin
from django.urls import path,include
from graphene_django.views import GraphQLView
from blog.schema import schema
from pages import views
from listings import views
from accounts import views
from contacts import views
from Ages import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('AgesVerification/', include('Ages.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header ="Koralcity control panel"
admin.site.index_title ="Administrators dashboard"
admin.site.site_title ="Control panel"

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.index , name='listings'),
    path('<int:listing_id>/',views.listing , name='listing'),
    path('search/',views.search , name='search'),

]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index , name='index'),
    path('about/', views.about , name='about'),
]

templates/pages/about.html
{% extends "base.html" %}

{% load static %}

{% block title %}
     About Us
{% endblock title %}

{% block content %}
   <section class="home_banner_area hero"  id="about">
    <div class="banner_inner d-flex align-items-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <div class="banner_content d-flex flex-md-row flex-column">
              <div class="banner-left text-md-right">
                <h1 class="text-uppercase">About Us</h1>
              </div>
              <div class="banner-right position-relative">
                <p>
                  RealEstate Limited.
                </p>
                <span class="main_btn mt-4 mt-md-0" href="#">
                  <a href="" >Home</a> 
                  <i class="fa fa-arrow-right mx-2"></i>
                  <a href="#">About</a> 
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
 <section class="statistic" id="about">

      <div class="container">
        <div class="row">
          <div class="col-12 col-lg-6">
            <h3>Our Company<br>RealEstate Limited</h3>
            <p>RealEstate Limited offers property owners, developers and buyers/renters a viable housing market. Customers can source and connect with professional agents for the most advanced and eco-friendly housing. Established in 2021, Gotham City believes everyone deserves a home with the most advanced technology and Eco-Friendly means. All lives matter.
              <h3>Why you should choose us</h3>
              <ul>  
                <li>1. We offer land verification and authentication.</li><br>
                <li>2. We sell, buy, and rent luxury properties at affordable rates.</li><br>
                <li>3. We offer a conducive platform for property owners to showcase their services.</li><br>
                <li>4. We have well trained professionals as consultants, developers and agents.</li><br>
                <li>5. We are budget friendly.</li>
                <li>  </li>
              </ul></p>
          </div>
          <div class="col-12 col-lg-6 statistic-wrapper">
            <div class="statistic-box text-center">
              <p>384</p>
              <p>Clients</p>
            </div>
            <div class="statistic-box text-center">
              <p>748</p>
              <p>Apartments</p>
            </div>
            <div class="statistic-box text-center">
              <p>14</p>
              <p>Awards</p>
            </div>
            <div class="statistic-box text-center">
              <p>24</p>
              <p>Employees</p>
            </div>
          </div>
        </div>
      </div>
    </section>
     <!------------------------------------------------ AGENTS SECTION -->
    <section id="agents" class="agents">
      <div class="container">
        <div class="row agents-services">
          <div class="col-12 agents-title">
            <h3>Meet Our Agents</h3>
            <p>They provide one of the most professional, informative, loyal and dedicated services<br> in the real estate industry. Client’s satisfaction is their number one priority.</p>
          </div>
        </div>
      
        
        <div class="row">
          {% if realtors %}
        {% for realtor in realtors %}
          <!-- Agent  -->
          <div class="col-12 col-md-12 col-lg-4">
            <div class="card">
              <div class="card-img", style="">
                <!-- Agent Image  -->
                <img src="{{realtor.photo.url}}" alt="">
              </div>
              <div class="appartment-info">
                <div class="appartment-title">
                  <!-- Agent Title  -->
                  <p>Realtor</p>
                </div>
                <div class="appartment-title">
                  <div class="left agent-name">
                    <!-- Agent name  -->
                    <p> {{realtor.name}}</p>
                  </div>
                  <div class="agent-social right flex-center">
                    <a href="#"><img src="{%static 'images/facebook.svg'%}" alt=""></a>
                    <a href="#"><img src="{%static 'images/twitter.svg'%}" alt=""></a>
                    <a href="#"><img src="{%static 'images/dribble.svg'%}" alt=""></a>
                  </div>
                </div>
              </div>
            </div>
            </div>
          {% endfor %}
          {% else %}
          <div class="col-md-12">
            <p>No Realtors Avialbale</p>
        </div>
      {% endif %}



        </div>
        </div>
      </section>
{% endblock content %}

templates/pages/agesverification.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="home_banner_area hero"  id="about">
    <div class="banner_inner d-flex align-items-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <div class="banner_content d-flex flex-md-row flex-column">
              <div class="banner-left text-md-right">
                <h1 class="text-uppercase">AGIS Verification</h1>
              </div>
              <div class="banner-right position-relative">
                <p>
                 Upload your documents and fill the contact form.
                </p>
                <span class="main_btn mt-4 mt-md-0" href="#">
                  <a href="" >Home</a> 
                  <i class="fa fa-arrow-right mx-2"></i>
                  <a href="#">About</a> 
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% csrf_token %}
   <section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-sign-in-alt"></i> AGIS Verification</h4>
            </div>
            <div class="card-body">
            	<!-- Alerts -->
            	{% include 'partials/_alerts.html' %}
              <form method="POST" enctype="multipart/form-data" action="">
                {% csrf_token %}
                 <div class="form-group">
                  <label for="username">Full Name</label>
                  <input type="text" name="name" class="form-control" required>
                </div>
                 <div class="form-group">
                  <label for="username">Email</label>
                  <input type="text" name="email" class="form-control" required>
                </div>
                 <div class="form-group">
                  <label for="username">Phone Number</label>
                  <input type="text" name="phone" class="form-control" required>
                </div>
                 <div class="form-group">
                  <label for="username">Document File: </label>
                 <input type="file" name="upload_file">
                </div>
                
                <button type="submit" class="main-btn pointer text-center animate">Upload</button>                
              </form>

              <p><a href="{% url 'pages:index' %}">Return to home</p></a>
              
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>
{% endblock content %}

templates/pages/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}


{% block header%}

   <div class="hero">
        <div class="container">
          <div class="hero-wrapper">
            <div class="title">
              <!-- Hero Title -->
              <h1>Find Your New<br>Modern Apartment </h1>
              <form action="{% url 'listings:search' %}">
              <div class="search lux-shadow">
                <!-- Search -->
                <input class="left" name="keywords" type="text" placeholder="Keyword" value="{{ values.keywords }}">
                <button class="search-btn left" type="submit">Search</button>
              </div>
            </form>
            </div>
            <div class="hero-image">
              <div class="hero-image-info light-bg flex-center">
                <div class="info flex-center">
                  <img src="" alt="">
                  <!-- Phone -->
                  <p><a href="{% url 'listings:search' %}"> Buy</p></a>
                </div>
                <div class="info flex-center">
                  <img src="" alt="">
                  <!-- Place -->
                  <p><a href="{% url 'listings:search' %}">Sell</p></a>
                </div>
                <div class="info flex-center">
                  <img src="" alt="">
                  <!-- Place -->
                  <p><a href="{% url 'Ages:Ages' %}">AGIS Verification</p></a>
                </div>
              </div>
            </div>
            <div class="slide-down text-center pointer">
              <a href="#about">
                 <p>Scroll Down</p> 
                <img src="{%static './images/scroll.svg'%}" alt="">
              </a>
            </div>
          </div>
        </div>
      </div>
{% endblock header%}


{% block content %}

  <!-- Alerts -->
              {% include 'partials/_alerts.html' %}
  <!-- Listings -->
   <section id="appartments" class="appartments">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h2>More Then 500+<br>Apartments For Sale & Rent</h2>
          </div>
        </div>
        <div class="row">
        {% if listings %}
           {% for listing in listings %}
              <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                  <img class="card-img-top" src="{{ listing.photo_main.url}}" alt="">
                  <div class="card-img-overlay">
                    <h2>
                      <span class="badge price Black-text">₦{{listing.price | intcomma}}</span>
                    </h2>
                  </div>
                  <div class="card-body">
                    <div class="listing-heading text-center">
                      <h4 class="text-primary">{{listing.title}}</h4>
                      <p>
                        <i class="fas fa-map-marker text-secondary Black-text"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                    </div>
                    <hr>
                    <div class="row py-1 text-secondary">
                      <div class="col-6">
                        <p> <i class="fas fa-th-large"></i> Type: {{listing.property_type}}</p></div>
                      <div class="col-6">
                       <p> <i class="fas fa-bath"></i> Bathroom: {{listing.bathrooms}}</p></div>
                    </div>
                    <div class="row py-1 text-secondary">
                      <div class="col-6 text-secondary">
                       <p> <i class="fas fa-car"></i> Garage: {{listing.garage}}</p></div>
                      <div class="col-6 text-secondary">
                       <p> <i class="fas fa-bed"></i> Bedroom: {{listing.bedrooms}}</p></div>
                    </div>
                    <a href="{% url "listings:listing" listing.id %}" class="btn main-btn pointer text-center animate">More Info</a>
                  </div>
                </div>
              </div>
           {% endfor %}
        {% else %}

        <div class="col-md-12">
          <p>No Listings Available</p>
        </div>

        {% endif %}
      </div>

       <div class="row">
        <div class="col-md-12">
          {% if listings.has_other_pages %}

            <ul class="pagination">
               {% if listings.has_previous %}
                  <li class="page-item">
                    <a href="?page={{listings.previous_page_number}}" class="page-link">&laquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                   </li>
               {% endif %}
               {% for i in listings.paginator.page_range %}
                 {% if listings.number == i %}

                  <li class="page-item active">
                    <a class="page-link">{{i}}</a>
                  </li>
                 {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                      </li>
                 {% endif %}
               {% endfor %}
               {% if listings.has_next %}
                  <li class="page-item">
                    <a href="?page={{listings.next_page_number}}" class="page-link">&raquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                   </li>
               {% endif %}
            </ul>

          {% else %}

          {% endif %}
        </div>
      </div>


      </div>
    </div>
  </section>

  <section id="services" class="py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-4">
          <i class="fas fa-home  fa-3x mr-3"></i>
          <hr>
          <h3>Consulting Services</h3>
          <p style=" text-align:justify-all;"> RealEstate Limited gives specialized investment and financial advice to clients looking to buy, sell or invest in property. We'll work closely with you throughout the process of buying and selling of your properties.</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-key fa-3x mr-3"></i>
          <hr>
          <h3>Property Management</h3>
          <p style=" text-align:justify-all;">At RealEstate Limited, we handle the operations, maintenance, and administration of properties rentals for the owners and also market rentals rates at competitive price while complying with rental laws.</p>
        </div>
        <div class="col-md-4">
          <i class="fas fa-money-bill-alt fa-3x mr-3"></i>
          <hr>
          <h3>Renting & Selling</h3>
          <p style=" text-align:justify-all;">Our property managers at RealEstate Limited set competitive rent prices and strategies to attract clients to the property for rent or sell very fast with the first impression on  potential clients . </p>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}