Ages/urls.py
from django.urls import path
from . import views
from Ages.views import model_form_upload


app_name = 'Ages'

urlpatterns = [
    path('', model_form_upload, name='Ages'),

]

contacts/urls.py
from django.urls import path
from . import views


app_name = 'contacts'

urlpatterns = [
    path('contact/', views.contact , name='contact'),

]

coralcity/urls.py
from django.contrib import admin
from django.urls import path,include
from graphene_django.views import GraphQLView
from blog.schema import schema
from pages import views
from listings import views
from accounts import views
from contacts import views
from Ages import views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls')),
    path('AgesVerification/', include('Ages.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True)),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header ="Koralcity control panel"
admin.site.index_title ="Administrators dashboard"
admin.site.site_title ="Control panel"

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.index , name='listings'),
    path('<int:listing_id>/',views.listing , name='listing'),
    path('search/',views.search , name='search'),

]

listings/models.py
from django.db import models
from datetime import datetime
from django.utils.timezone import timezone

from realtors.models import Realtor

# Create your models here.

class Listing(models.Model):
	realtor = models.ForeignKey(Realtor , on_delete=models.DO_NOTHING, blank=True)
	title = models.CharField(max_length=200)
	address = models.CharField(max_length=200)
	city = models.CharField(max_length=100)
	state = models.CharField(max_length=100)
	zipcode = models.CharField(max_length=20)
	description = models.TextField(blank=True)
	price = models.IntegerField()
	bedrooms = models.IntegerField()
	property_type =models.CharField(max_length=10)
	bathrooms = models.IntegerField()
	garage = models.IntegerField(default=0)
	sqft = models.IntegerField()
	lot_size = models.DecimalField(max_digits=5 , decimal_places=1)
	photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/' , blank=True)
	is_published = models.BooleanField(default=True)
	list_date = models.DateTimeField(default=datetime.now , blank=True)


	def __str__(self):
		return self.title;

listings/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse

from listings.choices import price_choices , bedroom_choices , state_choices, type_choices

from .models import Listing

# Create your views here
def index(request):
	listings = Listing.objects.all().order_by('-list_date').filter(is_published=True)
	paginator = Paginator(listings, 6)
	page = request.GET.get('page')
	paged_listings = paginator.get_page(page)
	return render(request,'listings/listings.html',{'listings' : paged_listings})


def listing(request , listing_id):
	listing = get_object_or_404(Listing , pk=listing_id)
	context = {
	  'listing' : listing
	}
	return render(request,'listings/listing.html',context)


def search(request):
	queryset_list = Listing.objects.order_by('-list_date')
	if 'keywords' in request.GET:
		keywords = request.GET['keywords']
		if keywords:
			queryset_list = queryset_list.filter(description__icontains=keywords)

	if 'city' in request.GET:
		city = request.GET['city']
		if city:
			queryset_list = queryset_list.filter(city__iexact=city)

	if 'state' in request.GET:
		state = request.GET['state']
		if state:
			queryset_list = queryset_list.filter(state__iexact=state)

	if 'bedrooms' in request.GET:
		bedrooms = request.GET['bedrooms']
		if bedrooms:
			queryset_list = queryset_list.filter(bedrooms__lte=bedrooms)

	if 'price' in request.GET:
		price = request.GET['price']
		if price:
			queryset_list = queryset_list.filter(price__lte=price)


	return render(request,'listings/search.html',{
		'listings' : queryset_list,
        'state_choices' : state_choices,
        'bedroom_choices' : bedroom_choices,
        'price_choices' : price_choices,
        'type_choices' : type_choices,
        'values': request.GET,
		})

templates/listings/listing.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<section class="home_banner_area hero"  id="about">
    <div class="banner_inner d-flex align-items-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <div class="banner_content d-flex flex-md-row flex-column">
              <div class="banner-left text-md-right">
                <h1 class="text-uppercase">Properties</h1>
              </div>
              <div class="banner-right position-relative">
                <p>{{listing.title}} |  {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                <span class="main_btn mt-4 mt-md-0" href="#">
                  <a href="" >Home</a> 
                  <i class="fa fa-arrow-right mx-2"></i>
                  <a href="#">Listing</a> 
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Alerts -->
              {% include 'partials/_alerts.html' %}
  <!-- Listings -->

  <!-- Listing -->
  <section id="listing" class="py-5">
    <div class="container my-5">
      <a href="{% url 'listings:listings' %}" class="btn main-btn pointer text-center animate mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{listing.photo_main.url}}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">
            {% if listing.photo_1 %}
            <div class="col-md-2">
             <a href="{{listing.photo_1.url}}" data-lightbox="home-images">
                <img src="{{listing.photo_1.url}}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_2 %}
            <div class="col-md-2">
              <a href="{{listing.photo_2.url}}" data-lightbox="home-images">
                <img src="{{listing.photo_2.url}}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_3 %}
            <div class="col-md-2">
              <a href="{{listing.photo_3.url}}" data-lightbox="home-images">
                <img src="{{listing.photo_3.url}}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_4 %}
            <div class="col-md-2">
              <a href="{{listing.photo_4.url}}" data-lightbox="home-images">
                <img src="{{listing.photo_4.url}}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_5 %}
            <div class="col-md-2">
              <a href="{{listing.photo_5.url}}" data-lightbox="home-images">
                <img src="{{listing.photo_5.url}}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_6 %}
            <div class="col-md-2">
              <a href="{{listing.photo_6.url}}" data-lightbox="home-images">
                <img src="{{listing.photo_6.url}}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
          </div>
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">₦{{listing.price | intcomma}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">{{listing.bedrooms}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">{{listing.bathroom}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-car"></i> Type:
                  <span class="float-right">{{listing.property_type}}
                  </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">{{listing.sqft}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Lot Size:
                  <span class="float-right">{{listing.lot_size}} Acres
                  </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">{{listing.list_date}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">{{listing.realtor.name}}
                  </span>
                </li>


              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
             {{listing.description}}
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{listing.realtor.photo.url}}" alt="Seller of the month">
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">Realtor name: {{listing.realtor.name}}</h6>
               <h6 class="text-secondary">Number: {{listing.realtor.phone}}</h6>
                <h6 class="text-secondary">Email: {{listing.realtor.email}}</h6>
            </div>
          </div>
          <button class="btn main-btn pointer text-center animate btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{% url "contacts:contact" %}">
            {% csrf_token %}
            {% if user.is_authenticated %}
                <input type="hidden" name="user_id" value="{{user.id}}">
            {% else %}
                <input type="hidden" name="user_id" value="0">
            {% endif %}
            <input type="hidden" name="realtor_email" value="{{listing.realtor.email}}">
            <input type="hidden" name="listing_id" value="{{listing.id}}">
            <div class="form-group">
              <label for="property_name" class="col-form-label">Property:</label>
              <input value="{{listing.title}}" type="text" name="listing" class="form-control">
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input {% if user.is_authenticated %} value="{{user.username}}" {% endif %}  type="text" name="name" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input {% if user.is_authenticated %} value="{{user.email}}"{% endif %}  type="email" name="email" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="phone" class="col-form-label">Phone:</label>
              <input {% if user.is_authenticated %} value="{{user.phone}}"{% endif %} type="text" name="phone" class="form-control">
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/listings/listings.html
{% extends "base.html" %}

{% load humanize %}


{% block content %}
<section class="home_banner_area hero"  id="about">
    <div class="banner_inner d-flex align-items-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <div class="banner_content d-flex flex-md-row flex-column">
              <div class="banner-left text-md-right">
                <h1 class="text-uppercase">Properties</h1>
              </div>
              <div class="banner-right position-relative">
                <p>More Then 500+ Apartment For Sell & Rent</p>
                <span class="main_btn mt-4 mt-md-0" href="#">
                  <a href="" >Home</a> 
                  <i class="fa fa-arrow-right mx-2"></i>
                  <a href="#">Properties</a> 
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


    <section id="appartments" class="py-5">
    <div class="container my-5">
      <div class="row">
          <div class="col-12">
            
          </div>
        </div>
        <div class="row">

        {% if listings %}
           {% for listing in listings %}
              <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                  <img class="card-img-top" src="{{ listing.photo_main.url}}" alt="">
                  <div class="card-img-overlay">
                    <h2>
                      <span class="badge price Black-text">₦{{listing.price | intcomma}}</span>
                    </h2>
                  </div>
                  <div class="card-body">
                    <div class="listing-heading text-center">
                      <h4 class="text-primary">{{listing.title}}</h4>
                      <p>
                        <i class="fas fa-map-marker text-secondary Black-text"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                    </div>
                    <hr>
                    <div class="row py-1 text-secondary">
                      <div class="col-6">
                        <p> <i class="fas fa-th-large"></i> Type: {{listing.property_type}}</p></div>
                      <div class="col-6">
                       <p> <i class="fas fa-bath"></i> Bathroom: {{listing.bathrooms}}</p></div>
                    </div>
                    <div class="row py-1 text-secondary">
                      <div class="col-6 text-secondary">
                       <p> <i class="fas fa-car"></i> Garage: {{listing.garage}}</p></div>
                      <div class="col-6 text-secondary">
                       <p> <i class="fas fa-bed"></i> Bedroom: {{listing.bedrooms}}</p></div>
                    </div>
                    <a href="{% url "listings:listing" listing.id %}" class="btn main-btn pointer text-center animate">More Info</a>
                  </div>
                </div>
              </div>
           {% endfor %}
        {% else %}

        <div class="col-md-12">
          <p>No Listings Available</p>
        </div>

        {% endif %}
      </div>

      <div class="row">
        <div class="col-md-12">
          {% if listings.has_other_pages %}

            <ul class="pagination">
               {% if listings.has_previous %}
                  <li class="page-item">
                    <a href="?page={{listings.previous_page_number}}" class="page-link">&laquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                   </li>
               {% endif %}
               {% for i in listings.paginator.page_range %}
                 {% if listings.number == i %}

                  <li class="page-item active">
                    <a class="page-link">{{i}}</a>
                  </li>
                 {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                      </li>
                 {% endif %}
               {% endfor %}
               {% if listings.has_next %}
                  <li class="page-item">
                    <a href="?page={{listings.next_page_number}}" class="page-link">&raquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                   </li>
               {% endif %}
            </ul>

          {% else %}

          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/listings/search.html
{% extends "base.html" %}

{% load humanize %}
{% block content %}

    <section id="appartments" class="appartments home_banner_area hero">
      <div class="container my-5">
        <div class="row">
          <div class="col-12 text-center white-text">
            <h1>Search for your Appartments<br>and make your inquiries  </h1>
          </div>
        </div>
        <div class="col-md-6 mx-auto">
          <form method="GET" action="{% url 'listings:search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)" value="{{ values.keywords }}">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" value="{{ values.city }}" class="form-control" placeholder="City">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" disabled="disabled">State (All)</option>
                  {% for key,value in state_choices.items %}
                       <option value="{{key}}"
                       {% if key == values.state %}selected="selected"{% endif %}
                       >{{value}}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Bedrooms</label>
                <select name="bedrooms" class="form-control">
                  <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                  {% for key,value in bedroom_choices.items %}
                       <option value="{{key}}"
                        {% if key == values.bedroom %}selected="selected"{% endif %}
                       >{{value}}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <select name="price" class="form-control">
                  <option selected="true" disabled="disabled">Max Price (All)</option>
                  {% for key,value in price_choices.items %}
                       <option value="{{key}}"
                       {% if key == values.price %}selected="selected"{% endif %}
                       >{{value}}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-primary main-btn pointer text-center animatebtn-block" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">

        {% if listings %}
           {% for listing in listings %}
              <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                  <img class="card-img-top" src="{{ listing.photo_main.url}}" alt="">
                  <div class="card-img-overlay">
                    <h2>
                      <span class="badge price Black-text">₦{{listing.price | intcomma}}</span>
                    </h2>
                  </div>
                  <div class="card-body">
                    <div class="listing-heading text-center">
                      <h4 class="text-primary">{{listing.title}}</h4>
                      <p>
                        <i class="fas fa-map-marker text-secondary"></i> {{listing.city}} {{listing.state}}, {{listing.zipcode}}</p>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                      <div class="col-6">
                        <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                      <div class="col-6">
                        <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
                    </div>
                    <div class="row py-2 text-secondary">
                      <div class="col-6">
                        <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                      <div class="col-6">
                        <i class="fas fa-bath"></i> Bathrooms: {{listing.bathroom}}</div>
                    </div>
                   
                    <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                  </div>
                </div>
              </div>
           {% endfor %}
        {% else %}

        <div class="col-md-12">
          <p>No Listings Available</p>
        </div>

        {% endif %}


      </div>
    </div>
  </section>
{% endblock content %}